### ISSUE TITLE
Unreadable text when errors contain source link

### ISSUE THREAD

**Issue by cowwoc** [krasa/GrepConsole#106]
By default ERROR lines are colored black foreground on light brown background. However, if the ERROR contains a source-link (e.g. output from a compiler error) then we end up with light blue foreground on a light brown background and the result is unreadable.
![screenshot](https://user-images.githubusercontent.com/633348/38563017-e1985b96-3ca9-11e8-9f6c-89854fb426c8.jpg)

**Comment by cowwoc** [comment]
Either change the default color to something that would work better with links, or suppress the special link foreground color for lines that get a special background color.

**Comment by krasa** [comment]
How about this:

![image](https://user-images.githubusercontent.com/1160875/39950343-a8e20406-5580-11e8-8142-4f0d74e0a935.png)

**Comment by krasa** [comment]
Or dark yellow for WARN 
![image](https://user-images.githubusercontent.com/1160875/39950438-58f9707c-5581-11e8-886e-1d203ffcfd1d.png)

**Comment by krasa** [comment]
And black for FATAL 👍 
![image](https://user-images.githubusercontent.com/1160875/39950564-46c43ab2-5582-11e8-8d7c-b54b4ee76854.png)

**Comment by cowwoc** [comment]
The first combination in the first response is the easiest to read, in spite of the fact that you used green for WARN which is kind of the opposite of what you want for warnings. That said, I'll take green for warnings any day of the week so long as the result is readable ;)

The only color combination I still find a bit hard to read is the links (light blue foreground) with a dark red background.

Would it looks weird if we avoid changing the background color for links (just color the leading text)?

**Comment by krasa** [comment]
Yeah that green is nice, but not for WARN :)

Dark yellow has bad contrast to background and to text, but I found a good alternative - violet. And red would maybe work better with lower brightness, but it will never be great against blue font:
![image](https://user-images.githubusercontent.com/1160875/39952109-6d86b4c2-5591-11e8-9a4a-16634efbc548.png)
It may not be great, but at least it is readable.

I just found out that you can actually do this: `File | Settings | Editor | Color Scheme | General |  Hyperlinks ` and add background there.
![image](https://user-images.githubusercontent.com/1160875/39952081-fa073c6a-5590-11e8-9553-d22d3a6ca80e.png)

**Comment by cowwoc** [comment]
Honestly, the best solution I've seen so far is violet as you suggested *and* disabling background colors for hyperlinks. The line is still visibly highlighted without changing the background color of links.
