### ISSUE TITLE
How to make Grep Console highlight run configurations?

### ISSUE THREAD

**Issue by gxcross** [krasa/GrepConsole#112]
In IntelliJ, if I run a configuration (grunt) the output to console is not colorized by Grep Console. However, if I right-click a word in the console output and "Grep" that, then everything is colorized properly. How do I make Grep Console run by default for my Run configurations?

Thanks!

**Comment by krasa** [comment]
Normally https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/execution/impl/ConsoleViewImpl.java#L276  should be called (that provides a coloring filter), if it is not, then JetBrains or whoever makes Grunt plugin could fix it. There is nothing I can do.



But maybe it would be possible to call this manually - not automatically, as a workaround https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/execution/impl/ConsoleViewImpl.java#L850
You would have to right click in the console and select an action which would add a coloring filter.

**Comment by gxcross** [comment]
darn, okay thanks.. was hoping it was just a configuration error on my part. Odd thing is that in the console, I see the "grep console" button.. so it's there, but it's not applying it to the output.

**Comment by krasa** [comment]
"grep console" button triggers my code, and I create a whole new console correctly, that's why it's there :)

Looking at it, maybe it will be possible to do it automatically. I will try it tomorrow.

**Comment by gxcross** [comment]
awesome, thank u!

**Comment by krasa** [comment]
Try to install this https://github.com/krasa/GrepConsole/releases/download/8.3.162.000.0/GrepConsole.zip  (without extracting)

**Comment by gxcross** [comment]
omg!! you are awesome, it works! thank you so much! 

![image](https://user-images.githubusercontent.com/10765800/42348590-d521982a-805e-11e8-86ef-6df1b98f015a.png)

**Comment by gxcross** [comment]
wow, even saw you updated the plugin already too! thx again for your quick reply and responsiveness!!

**Comment by krasa** [comment]
No problem! And thanks for reporting it.
