### ISSUE TITLE
Dark theme compatibility

### ISSUE THREAD

**Issue by Vampire** [krasa/GrepConsole#114]
The out-of-the-box settings of your plugin are not very dark theme friendly.
If you just install the plugin and open the console, the TRACE level logging e. g. is totally unreadable:

![grafik](https://user-images.githubusercontent.com/325196/42632852-dcdc7870-85de-11e8-8af4-c2170ce994a4.png)

With highlighting disabled it looks like this

![grafik](https://user-images.githubusercontent.com/325196/42632871-f29ff254-85de-11e8-974c-18088e307528.png)

**Comment by krasa** [comment]
Try to click on reset settings

**Comment by Vampire** [comment]
You mean "Reset all to default"?
Doesn't change anything.

**Comment by krasa** [comment]
Ok. TRACE has lower contrast by design, but it may be too low for you and your monitor. So just change it. 

And if you have a better idea how to color it, then tell me.

**Comment by Vampire** [comment]
It is fine if you have a light theme where it is black on white.
But on a dark theme?
On what monitor does black on dark grey have enough contrast to be readable properly? o_O

**Comment by krasa** [comment]
I have used it that way for years just fine, on at least 6 different monitors with a contrast and brightness way down.

**Comment by Vampire** [comment]
Can you actually read the text in my first screenshot sufficiently?

**Comment by Vampire** [comment]
Not the DEBUG lines, the TRACE lines I mean

**Comment by krasa** [comment]
Sure, when I open it in fullscreen so I have no white around. 
![image](https://user-images.githubusercontent.com/1160875/42634632-00bcd7f8-85e4-11e8-8cd2-6a579a81101d.png)

**Comment by Vampire** [comment]
I find this unreadable even on fullscreen, but ok.
Thought it might just be a bug as many ppl don't use TRACE level logging or don't enable it.
If it is intentionally that way, then I simply consider changing it or leave the hightlighting disabled.
