### ISSUE TITLE
Apply does almost nothing?

### ISSUE THREAD

**Issue by Vampire** [krasa/GrepConsole#116]
Maybe I just misunderstand, but what should the Apply button do?
Changing the search term and clicking "Apply" or pressing "Enter" does change the tab title to the new search string, but nothing else happens.
Is this expected or should there happen more, or is there happening more I just don't realize?

**Comment by krasa** [comment]
Reload - alt +enter  reloads the console, apply changes the settings only for future lines.

**Comment by Vampire** [comment]
Ah, nice I see.
Then let's morph this into an improvement request to mention this in the tooltip.
For `Reload` it mentions in the tooltip what it does and how to invoke it from keyboard.
For `Apply` it only mentions how to invoke it, not what it does.
