### ISSUE TITLE
Grep - use ANSI color codes from the source console 

### ISSUE THREAD

**Issue by Vampire** [krasa/GrepConsole#119]
The way I configured log4j it outputs log lines colored with ANSI color codes.

The IJ console is capable of properly showing these colors, also different according to light-theme / dark-theme so that you don't end up with black text on black background.

Example with light theme "Default" (GrepConsole Highlighting disabled):
![grafik](https://user-images.githubusercontent.com/325196/42636163-558fc7fa-85e8-11e8-99ef-a4d566c7ab15.png)

Same region with dark theme "Darcula" (GrepConsole Highlighting disabled):
![grafik](https://user-images.githubusercontent.com/325196/42636202-73c1b77e-85e8-11e8-9a18-811b2aa08f5e.png)

Now when opening a grep console, the coloring is lost.
![grafik](https://user-images.githubusercontent.com/325196/42636289-b3788096-85e8-11e8-8af4-21009e427966.png)

It would be nice if the grep console could also show the ANSI colors the same ways as the standard console shows them, also adaptive to light vs. dark theme.

**Comment by danielgomezrico** [comment]
This feature would be awesome, Im using https://pub.dev/packages/fimber and it prints things with this format without any effort.
