### ISSUE TITLE
Grep console not updating

### ISSUE THREAD

**Issue by SirWellington** [krasa/GrepConsole#120]
I have been using the plugin for years. I have noticed that when using AppCode, the grep console does not automatically update results from the source console. I have to manually hit "Reload" for it to update.

This has only been happening recently. 

Any suggestions?

**Comment by krasa** [comment]
Well, if you could, then debugging of the plugin is probably the only way to find out what is happening.
Maybe it is using some other API to add text to the console, which does not go through filters, or there is some other input filter which is used instead. (https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/execution/impl/ConsoleViewImpl.java#L563).

I do not have Mac, so I cannot help. The other alternative is to ask JetBrains for help.

**Comment by SirWellington** [comment]
Thank you @krasa – let me take a look, as this is starting to bug me.

**Comment by SirWellington** [comment]
@krasa Can you please show me how to do debug this from App Code?

**Comment by SirWellington** [comment]
Tried old version @krasa . Also tried completely uninstalling, removing all plugins, clearing caches, and still same issue.

**Comment by SirWellington** [comment]
It's working now! I'm not sure what I did, but I tried deleting the `.idea` folder, which included GrepConsole configuration. Perhaps that did something.

**Comment by krasa** [comment]
that's strange, let me know if it happens again
