### ISSUE TITLE
sound not played

### ISSUE THREAD

**Issue by erlangp** [krasa/GrepConsole#122]

**Comment by krasa** [comment]
not enough details

**Comment by erlangp** [comment]
i set an .wav sound but the sound not played

**Comment by erlangp** [comment]
@krasa can u give me screenshot sir.. on my windows not working :(

**Comment by krasa** [comment]
![image](https://user-images.githubusercontent.com/1160875/44736502-b081c380-aaef-11e8-901a-bf78b8b8661b.png)

**Comment by garzy** [comment]
Try with another and smaller .wav file. I'm having the same error with 512KB .wav file and I changed my error sound to a 130KB .wav file and now it's working

**Comment by krasa** [comment]
Win 10 works fine with 1107kB C:/Windows/Media/Ring05.wav

**Comment by garzy** [comment]
Win 10 also ;)
