### ISSUE TITLE
How to permanently close a grep console

### ISSUE THREAD

**Issue by SteveSteinitz** [krasa/GrepConsole#125]
Hi Vojtěch,

I created a couple of grep consoles with your excellent plugin.  They are part of my React-Native run configuration.  

I'm not clear on how to permanently close them.  When I launch WebStorm they reappear.  I'm sure it's something simple, but I can't work it out after 5 minutes of trying and looking around :)

**Comment by krasa** [comment]
There is Pin button, also just closing them manually by middle click or context menu should work.

**Comment by krasa** [comment]
![image](https://user-images.githubusercontent.com/1160875/45619917-4ff4ff00-ba7b-11e8-85df-810aaa8a1561.png)

**Comment by SteveSteinitz** [comment]
Thanks for showing me the pin.  However I still have too many grep consoles.
![screen shot 2018-09-21 at 3 07 09pm](https://user-images.githubusercontent.com/42371298/45861508-4687d180-bdb0-11e8-9352-524b01ebde3c.png)
I unpin them and close them over and over, but they return.

I hope this report is useful.

ps. one thing I really like about your consoles is they don't show the useless urls on the right-hand side which only waste space and cause buggy line wrapping.  Please don't 'fix' that :)

**Comment by krasa** [comment]
That's strange, perhaps I should add some logging... 

Also when you press the Pin icon, does it get unselected? Because that means that it really is unpinned...
![image](https://user-images.githubusercontent.com/1160875/45864779-6fda3a80-bd7b-11e8-9243-d977ec956a29.png)


What do you mean by 'useless urls'?

**Comment by SteveSteinitz** [comment]
Thanks for following up.  Yes the pin icons get unselected.  Then I close the grep tabs, but they reappear on next run (or debug) of the run configuration.

I've taken a screenshot of the useless urls.  I've asked JetBrains to get rid of them but they declined.  Having them gone was an unexpected delight from using your plugin.  In fact, now I have a regex grep, '.+', which shows all messages but omits the urls.

![useless urls](https://user-images.githubusercontent.com/42371298/45881226-ef085680-bded-11e8-8c43-b38c7123fb69.png)

Note the 'useless urls' in blue, on the right.

**Comment by krasa** [comment]
I've never seen those urls, amazing. 

Please try this:
- install (without unziping) [GrepConsole.zip](https://github.com/krasa/GrepConsole/files/2405748/GrepConsole.zip)  (in new IDEs you can just drag it into the editor and it gets installed)
- enable debug log by adding `#krasa.grepconsole` in `Help | Debug log settings...`
- post the result after you unpin something and hit rerun. ( you can use `Help | Tail Log in Console`)

**Comment by SteveSteinitz** [comment]
Thanks for your help.  Those urls are annoying.  I'm surprised you've never seen them.  Hmmm.

I installed the new version.  I unpinned and closed the six grep consoles.  They didn't re-appear on run,  but all six re-appeared when I relaunched WebStorm then ran.

I apologize for the size of the attached log fragment.  I tried to use grep console to pare it down but I wasn't able to specify just the right regex in sixty seconds :)

[krasa.log.zip](https://github.com/krasa/GrepConsole/files/2407360/krasa.log.zip)

I hope it's useful.

**Comment by krasa** [comment]
Well, this looks similar, only it's Node, not React.
![image](https://user-images.githubusercontent.com/1160875/45920582-80d39a80-bea6-11e8-82a4-cee269066603.png)

**Comment by krasa** [comment]
This should be even better [GrepConsole.zip](https://github.com/krasa/GrepConsole/files/2408060/GrepConsole.zip). 
Also try to get rid of all the old pins, even by deleting them via OS from `project/.idea/GrepConsole.xml`:

**Comment by SteveSteinitz** [comment]
Your latest version works better.  Thank you.  Let me test it for a few days and report back.  

I did notice one minor problem unrelated to this discussion.  I'll show you here but I'm happy to open a new issues if you prefer.

In the GrepConsole settings one of the actions is undefined.  Perhaps that's intentional.

![screen shot 2018-09-23 at 11 11 03am](https://user-images.githubusercontent.com/42371298/45924366-c5604400-bf41-11e8-81c6-2e0b6dd8b52b.png)

I hope this report is useful.

**Comment by krasa** [comment]
It is still not right, I am fixing it...


That default line was meant as an example, maybe bad idea, I changed it.

**Comment by krasa** [comment]
here: [GrepConsole.zip](https://github.com/krasa/GrepConsole/files/2408635/GrepConsole.zip)

**Comment by krasa** [comment]
Seems fixed to me, let me know if it's not. Thanks.
