### ISSUE TITLE
Add simple mode

### ISSUE THREAD

**Issue by Lewik** [krasa/GrepConsole#126]
I need to grep (filter) by multiple words (class names) in one console. I need to write regex. Simple, but not usefull. Can you add checkbox for simple mode that will check words separated by space?
Like `some words` will act like `(some|words)` with Regex checkbox

**Comment by Lewik** [comment]
My idea is similar to yours. Your plugin allows to grep by one word very quickly and this is awesome. But how to filter by multiple words as quickly as by one word? What do you think about it?

**Comment by krasa** [comment]
Doable, but GUI would be a problem.
