### ISSUE TITLE
Make disabled config lines more distinguishable

### ISSUE THREAD

**Issue by robbyki** [krasa/GrepConsole#128]
Thank you for a great plugin. Trying to figure out how to filter out unwanted lines though. What is the setting for filtering out anything without the string `0.9.94` as an example. I keep getting everything printed it out. 
![screenshot from 2018-10-20 10-26-17](https://user-images.githubusercontent.com/1027357/47256744-c4440900-d452-11e8-8559-960bf08c46ae.png)

**Comment by krasa** [comment]
Thanks for the donation.

Highlighting is done after input filtering, so you need to do it like this:
![image](https://user-images.githubusercontent.com/1160875/47257018-b0b39500-d488-11e8-83d3-f862f6b7d77d.png)

**Comment by robbyki** [comment]
Sorry if this is incredibly silly mistake I'm making but how come this isn't just outputing in the console ONLY lines with the string `jline` in it as a substring? 
![screenshot from 2018-10-20 12-05-49](https://user-images.githubusercontent.com/1027357/47257816-8e0d8600-d460-11e8-8a38-225b8a486b7b.png)

**Comment by krasa** [comment]
well, it should. Maybe increase 'Match only first N characters...'? Or post an example.

**Comment by robbyki** [comment]
thank you. I knew it was something silly. You're right. Visually, it might make sense to call out inactive lines. A lot to look at on that one settings window. :)

**Comment by krasa** [comment]
Fixed by https://github.com/krasa/GrepConsole/commit/42c8bce03f20b88364093a3378010d1e912ca1df
![image](https://user-images.githubusercontent.com/1160875/58113100-21748880-7bf5-11e9-97ab-4c7e23cfa9b5.png)
