### ISSUE TITLE
Grep console not working in AppCode

### ISSUE THREAD

**Issue by SirWellington** [krasa/GrepConsole#129]
In reference to #120 

Unfortunately, this issue is happening again. I've tried everything I can think of. I will have to try and debug the plugin like you suggested.

**Comment by SirWellington** [comment]
I have tried debugging. Unfortunately I can't seem to debug the plugin off AppCode. 

I get a whole bunch of compile-time errors when I link it to AppCode's SDK.

![screen shot 2018-10-22 at 10 07 36 am](https://user-images.githubusercontent.com/992646/47306817-562e4c00-d5e2-11e8-8c0d-392a116207fd.png)

Seems to debug just fine from IntelliJ though.

**Comment by krasa** [comment]
Setup the SDK like this:
![image](https://user-images.githubusercontent.com/1160875/47307142-8ef41280-d62e-11e8-8c26-3d80a7112e21.png)

**Comment by krasa** [comment]
You could setup the SDK from IntelliJ Community, and JRE from  AppCode, or comment/remove those classes.

**Comment by SirWellington** [comment]
@krasa Just tried your tip. It worked and I was able to debug the plugin. 

The `GrepCopyingFilterSyncListener.process()` function is only getting called when a grep tab is first opened, and not for subsequent events. 

### Regular Console
![screen shot 2018-10-22 at 11 56 11 am](https://user-images.githubusercontent.com/992646/47312634-be385e80-d5f1-11e8-921c-2251624e85be.png)

### Grep Console
![screen shot 2018-10-22 at 11 56 29 am](https://user-images.githubusercontent.com/992646/47312641-c1334f00-d5f1-11e8-9e66-142204fb8185.png)

As you can see, none of the new events are picked up in the Grep Tab.

![screen shot 2018-10-22 at 11 55 52 am](https://user-images.githubusercontent.com/992646/47312669-d3ad8880-d5f1-11e8-9f6e-cf88f3183576.png)

**Comment by krasa** [comment]
Check if .`GrepConsoleInputFilterProvider#getDefaultFilters` is called when you run the app.

**Comment by krasa** [comment]
I suspect that `com.intellij.execution.impl.ConsoleViewImpl#print(java.lang.String, com.intellij.execution.ui.ConsoleViewContentType)` might be overriden. and not call InputFilters  - `com.jetbrains.commandInterface.console.CommandConsole`  does that.

**Comment by SirWellington** [comment]
`GrepConsoleInputFilterProvider.getDefaultFilters()` was called. 
`CompositeInputFilter#applyFilter` was also called. See attached.

![screen shot 2018-10-22 at 2 44 04 pm](https://user-images.githubusercontent.com/992646/47321475-c56b6680-d609-11e8-83c1-43bf15b099f7.png)

![screen shot 2018-10-22 at 2 44 11 pm](https://user-images.githubusercontent.com/992646/47321478-c8665700-d609-11e8-98a6-4170717283cb.png)

![screen shot 2018-10-22 at 2 44 19 pm](https://user-images.githubusercontent.com/992646/47321487-cdc3a180-d609-11e8-8f47-c2539b372a76.png)

![screen shot 2018-10-22 at 2 44 25 pm](https://user-images.githubusercontent.com/992646/47321494-d2885580-d609-11e8-9211-204bd07412e2.png)

![screen shot 2018-10-22 at 2 48 10 pm](https://user-images.githubusercontent.com/992646/47321512-e16f0800-d609-11e8-9f9d-91dc952ab694.png)


![screen shot 2018-10-22 at 2 48 30 pm](https://user-images.githubusercontent.com/992646/47321517-e469f880-d609-11e8-8280-05e8dd8778dc.png)

**Comment by SirWellington** [comment]
The `result = filter.applyFilter(text, contentType);` line is returning null for both filters that I am seeing.

![screen shot 2018-10-22 at 2 57 40 pm](https://user-images.githubusercontent.com/992646/47321874-fbf5b100-d60a-11e8-9b6d-d453ebe282df.png)

![screen shot 2018-10-22 at 2 57 58 pm](https://user-images.githubusercontent.com/992646/47321879-fe580b00-d60a-11e8-8223-7252ad0b3ab4.png)

**Comment by krasa** [comment]
Everything looks fine unless there are some other filters in those InputFilterWrappers.
The important thing is that `krasa.grepconsole.filter.GrepCopyingFilter#applyFilter` is called, and then you should be able to step through the code and see where it goes wrong.

**Comment by SirWellington** [comment]
Dug some more. Looks like there are multiple `GrepCopyingFilter` instances running around. One of them has the listener registered, but the others do not.

![screen shot 2018-10-22 at 4 32 50 pm](https://user-images.githubusercontent.com/992646/47325392-5c3f1f80-d618-11e8-91b9-507f67baa609.png)

The one that is getting called does not have any listeners registered. Do you know why that might be?

**Comment by krasa** [comment]
The one that has it, should be for the console from which you are grepping.

If not, then perhaps it was unregistered by:
https://github.com/krasa/GrepConsole/blob/278a868c810636d6b7f821f5b208b1b3beb9bbf0/src/krasa/grepconsole/grep/OpenGrepConsoleAction.java#L178
Or a wrong instance was used at some point.
- neither of that should happen

**Comment by SirWellington** [comment]
@krasa I put on a breakpoint on `removeListener()`, and I know that wasn't called. So it must be the other thing. 

This is weird. I suspect the AppCode is using a different platform jar which might be breaking tings.

**Comment by krasa** [comment]
That must mean that hashcode is broken and this does not work
https://github.com/krasa/GrepConsole/blob/fe78e7bb8284cba3897a7e999bef3a03cc774663/src/krasa/grepconsole/plugin/ServiceManager.java#L86

**Comment by SirWellington** [comment]
I temporarily hacked it by setting the `copyingListeners` field to `static`, and then doing: 
```java
public void addListener(GrepCopyingFilterListener copyingListener) {
	    if (copyingListeners.contains(copyingListener)) return;
		copyingListeners.add(copyingListener);
}

```
on [GrepCopyingFilter.java#L41](https://github.com/krasa/GrepConsole/blob/fe78e7bb8284cba3897a7e999bef3a03cc774663/src/krasa/grepconsole/filter/GrepCopyingFilter.java#L41)

@krasa What do you recommend we try next?

**Comment by krasa** [comment]
I will try to set up a VirtualBox with MacOS and reproduce it.

**Comment by krasa** [comment]
Try to add this thing: https://github.com/krasa/GrepConsole/commit/08beae1b9284ab465d4eb2a2cb316a2d93d9af8f

I think it is more probable than broken JVM, and I still did not make macOs work.

**Comment by SirWellington** [comment]
@krasa So far so good. Looks like that commit did the trick. Thanks.
