### ISSUE TITLE
Enhancement: Support of 256 (8-Bit) colors, e.g. \u001B[38;5;196m

### ISSUE THREAD

**Issue by softmonaut** [krasa/GrepConsole#13]
Hi,

I really love your plugin!
I suggest extending the ansi colors formats by supporting 8-bit colors, e.g. \u001B[38;5;196m for a light red (but not bold) color.
Here's a nice text on that topic: http://bitmote.com/index.php?post/2012/11/19/Using-ANSI-Color-Codes-to-Colorize-Your-Bash-Prompt-on-Linux

Best regards
Jörg

**Comment by krasa** [comment]
closing due to #39

**Comment by piotr-dobrogost** [comment]
I raised this as https://youtrack.jetbrains.com/issue/IDEA-137065
Please vote.

**Comment by piotr-dobrogost** [comment]
@krasa 
Thanks for voting.
Btw, do you have any plans to ask for an API which would allow plugin to get raw output (with escape sequences)?

**Comment by krasa** [comment]
Nope, what for? I have never used ANSI anyway :)
