### ISSUE TITLE
[Bug] Tail File in Console immediatly closes/goes empty

### ISSUE THREAD

**Issue by xetra11** [krasa/GrepConsole#138]
When I use Tail File in Console it happens since yesterday that my log output disappears completly. I already reinstalled, reset all grep highlight rules etc.

I can not figure out what the issue is here.

Reproduction steps are documented by this gif animation:

https://gph.is/g/E11LQdE

**Comment by krasa** [comment]
try this:
![image](https://user-images.githubusercontent.com/1160875/53458464-7f4e6580-3a36-11e9-8083-2a5279808805.png)

**Comment by xetra11** [comment]
will try this tonight

**Comment by xetra11** [comment]
gosh that fixed it. thanks
