### ISSUE TITLE
GREP icon doesn't show up in ultim Intellij 2019/Angular project

### ISSUE THREAD

**Issue by docertabum** [krasa/GrepConsole#140]
Hello,
can anybody confirm, that this plugin behaves differently in 2018.3.6 & 2019.1(.1)?
In 2019 this plugin doesn't appear in all "scenarios" it use to appear in 2018.
On screenshots below (2018 vs 2019) for example this is noticeable in case of running Angular application. GREP icon doesn't show up in RUN tab.

In case of java application, grep icon appears in RUN tab as expected.

Thank you.

2019 ![ultimate_2019 1 1](https://user-images.githubusercontent.com/588442/56361707-56ea1880-61e8-11e9-9317-3dfec27bdffe.jpg) 2018 ![ultimate_2018 3](https://user-images.githubusercontent.com/588442/56361708-56ea1880-61e8-11e9-8895-d6bd2bfdd63b.jpg)

**Comment by krasa** [comment]
Are you using this? https://plugins.jetbrains.com/plugin/6971-angularjs


Considering other icons are missing too, they probably screwed something.

**Comment by docertabum** [comment]
ah, ok. I reported the issue to JB. Thanks!

**Comment by krasa** [comment]
Is this what you see when you right click?
![image](https://user-images.githubusercontent.com/1160875/56385328-10fc7700-621f-11e9-94ef-7a7d53fcd191.png)

Because that is not a normal console, it is a terminal. And there is no way to add buttons. They must have switched to it in 2019.

**Comment by docertabum** [comment]
seems like JB closed it as third party problem... :\
https://youtrack.jetbrains.com/issue/IDEA-211272#focus=streamItem-27-3421030.0-0

**Comment by krasa** [comment]
Well, yeah, you reported that a third party plugin has a problem, not that all the buttons are missing :)
