### ISSUE TITLE
Clion shutting down when using GrepConsole

### ISSUE THREAD

**Issue by FreeYourSoul** [krasa/GrepConsole#141]
Grep console doesn't work for a few months, I am on Fedora 29 using the latest version of Clion (2019.1.2). The console doesn't change colour, and when trying to modify the grep console settings. Clion shut down without notice nor giving exception information.
This happens

 when I want to change the colour of a match by clicking the colour button (which is supposed to display to colour selection palette.

I installed the latest GrepConsole version (v 9.0.162.000.2)

**Comment by krasa** [comment]
Anything in the log, or some crash dump? what JRE is used? Post Menu | Help | About

**Comment by krasa** [comment]
Does changing colors work in File | Settings | Editor | Color Scheme | General?

**Comment by FreeYourSoul** [comment]
Hello,

Not it appears changing the color in File | Settings | Editor | Color
Scheme | General produce the same bug.

Is it a Clion bug more than the plugin itself ?

Le lun. 22 avr. 2019 à 12:08, Vojtěch Krása <notifications@github.com> a
écrit :

**Comment by FreeYourSoul** [comment]
Ps: No log/dump generated, at least not found by coredumpctl

Le lun. 22 avr. 2019 à 21:17, Quentin Balland <ballandfys@gmail.com> a
écrit :

**Comment by FreeYourSoul** [comment]
I have a core file but its size doesn't allow me to send it via github (>10MB)

**Comment by krasa** [comment]
https://bbs.archlinux.org/viewtopic.php?pid=1678706#p1678706
https://youtrack.jetbrains.com/issues?q=com.intellij.ui.ColorPicker$DefaultColorPipette.isAvailable()

OpenJDK bug, try to use JetBrains JRE

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/JBR-254#focus=streamItem-27-3392409.0-0
