### ISSUE TITLE
UI is not visible

### ISSUE THREAD

**Issue by cattrap** [krasa/GrepConsole#142]
When I click on the grep console icon, a window pops up, but none of the content is visible.  When I move my mouse around the window the controls start to appear, but I can only see some of them.  Here is a screenshot: https://imgur.com/a/jBk2Bhy  I thought this might be due to my theme, so I tried with just setting it to "intellij" and it did the same thing.  I'm hoping there's something I can do to be able to use this plugin, it looks very useful.  Any help is appreciated!

Oh, also this is on Intellij Ultimate 2019.1 with xmx set to 2gb.

**Comment by krasa** [comment]
That's strange, and everything else in the IDE works fine?

Menu | Help | About > copy it here

**Comment by krasa** [comment]
I think it will be some platform issue anyway, OS/JRE/IDE bug.

**Comment by cattrap** [comment]
Yeah, I haven't had any other problems.  Here is the help | about info:

IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
Licensed to <me>
Subscription is active until August 23, 2019
JRE: 12+33 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0

**Comment by krasa** [comment]
Do you have some theme plugins?
JRE: 12+33 amd64? what is that?
Could you try JetBrains JVM? It is better anyway. 


Here is me and it is totally fine:

IntelliJ IDEA 2019.1.1 (Community Edition)
Build #IC-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by krasa** [comment]
still a problem?
