### ISSUE TITLE
Grep Console works for Run but is disabled for Debug

### ISSUE THREAD

**Issue by OriginalBitFlipper** [krasa/GrepConsole#143]
Hi,

Grep Console works fine in a console with the output of a configuration that was initiated via **Run** (e.g. **Run | Run 'foo'**). However, for a configuration that was initiated via **Debug** (e.g. **Run | Debug 'foo'**), the **Grep** option is grayed out in the context menu for that console window.

Is this the expected behavior? Or is there a setting I can configure for it to work in a Debug console's output as well?

I don't think this should be relevant, but just in case... I'm doing remote debugging where both **Run** and **Debug** execute remotely on a Ubuntu VM.

Thanks in advance for any help with this.

PyCharm 2019.1.1 (Professional Edition)
Build #PY-191.6605.12, built on April 3, 2019
JRE: 11.0.2+9-b159.34 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by krasa** [comment]
which Run Configuration type does that?

**Comment by OriginalBitFlipper** [comment]
Just straight up Python. Pretty much exactly as shown in the menu in step 2 [here](https://www.jetbrains.com/help/pycharm/creating-and-editing-run-debug-configurations.html).

**Comment by krasa** [comment]
Try to install this:
[GrepConsole.zip](https://github.com/krasa/GrepConsole/files/3126169/GrepConsole.zip)

**Comment by OriginalBitFlipper** [comment]
Excellent, that appears to have worked!

Thanks for the quick response :)

**Comment by krasa** [comment]
No problem. Thanks for reporting it :)
