### ISSUE TITLE
IJ 2019.2 Grep support for new Maven build tool window

### ISSUE THREAD

**Issue by fengchangsheng** [krasa/GrepConsole#148]
**Describe the bug**
console can't open the grep option.

![grep](https://user-images.githubusercontent.com/8806582/62021135-5c4bfb80-b1f8-11e9-862d-2a46a6b50386.jpg)

**Comment by krasa** [comment]
need details

**Comment by fengchangsheng** [comment]
> need details

Just can't open the grep tab in the console.

**Comment by krasa** [comment]
What console? What Run Configuration [e.g. JAR Application]?

**Comment by fengchangsheng** [comment]
> What console? What Run Configuration [e.g. JAR Application]?

Use in IntelliJ IDEA :

=== About ===
Build version: IntelliJ IDEA 2019.2 Build #IU-192.5728.98 July 23, 2019
Java version: 11.0.3+12-b304.10amd64
Operating System: Windows 10 (10.0, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 4
Used memory: 750Mb 
Free memory: 228Mb 
Total memory: 978Mb 
Maximum available memory: 978Mb

**Comment by krasa** [comment]
Try this: https://github.com/krasa/GrepConsole/releases/download/9.7.162.000.0/GrepConsole.zip

If it still does not work, then provide a screen like this https://raw.githubusercontent.com/krasa/GrepConsole/master/screenIssue.png

**Comment by fengchangsheng** [comment]
> Try this: https://github.com/krasa/GrepConsole/releases/download/9.7.162.000.0/GrepConsole.zip
> 
> If it still does not work, then provide a screen like this https://raw.githubusercontent.com/krasa/GrepConsole/master/screenIssue.png

It still does not work:
[https://github.com/fengchangsheng/Issue-img/blob/master/idea_console.png](url)

**Comment by krasa** [comment]
Main menu | Help | Find Action... -> Registry... ->  disable `maven.build.tool.window.enabled`

**Comment by fengchangsheng** [comment]
> maven.build.tool.window.enabled

Thank u very much, u are god.

**Comment by krasa** [comment]
This should fix it:

https://github.com/krasa/GrepConsole/releases/download/9.8.162.000.0/GrepConsole.zip
