### ISSUE TITLE
Unable to use on Goland 2019.2

### ISSUE THREAD

**Issue by adzimzf** [krasa/GrepConsole#153]
**Describe the bug**
I can't use this on debug / run on Goland 2019.2
But when I run the unit test it still works

**Screenshots**
![image](https://user-images.githubusercontent.com/17941719/65485215-6bcf8400-decb-11e9-9f73-faae1fe9e12e.png)

**Comment by ltto** [comment]
# Does not support golangd
# by
GoLand 2019.2.5
Build #GO-192.7142.48, built on November 8, 2019
Licensed to **********
Subscription is active until June 5, 2020
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true
Non-Bundled Plugins: CMD Support, GrepConsole, com.intellij.apacheConfig, com.jetbrains.plugins.ini4idea, io.protostuff.protostuff-jetbrains-plugin, mobi.hsz.idea.gitignore, net.vektah.codeglance, org.jetbrains.plugins.sass, izhangzhihao.rainbow.brackets, org.toml.lang

**Comment by nvidhub** [comment]
友情提示：macos goland 2019.2 无法使用 Grep Console。

**Comment by krasa** [comment]
goland 2020.1 works fine for me.

**Comment by krasa** [comment]
![image](https://user-images.githubusercontent.com/1160875/79921294-39badc00-8432-11ea-870a-97ff89b5e599.png)

**Comment by gonejack** [comment]
Grep console 10.1.201.4515.0 is not working any more after Go Plugin upgraded to 201.7223.82.165 today in go project's run windows on IntelliJ 2020.1.1.

**Comment by adzimzf** [comment]
solved by https://github.com/krasa/GrepConsole/issues/175
