### ISSUE TITLE
"Grep" menu item disabled in RunDashboard

### ISSUE THREAD

**Issue by waypoint100** [krasa/GrepConsole#154]
![image](https://user-images.githubusercontent.com/5413689/67444056-4f9f2f80-f5bc-11e9-833a-3986335b65a9.png)

It works fine in regular "Run" or "Debug" windows, but not in "Run Dashboard"

IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 27, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

**Comment by krasa** [comment]
What is RunDashboard ?

**Comment by waypoint100** [comment]
It's one of the new features in Intellij IDEA (not sure about other products like PyCharm):
![image](https://user-images.githubusercontent.com/5413689/67445873-5b422480-f5c3-11e9-8210-5657d863b929.png)

**Comment by waypoint100** [comment]
p.s. colorer works fine in Run Dashboard, it's just "Grep" disabled for some reason:
![image](https://user-images.githubusercontent.com/5413689/67446009-e3c0c500-f5c3-11e9-83b0-a022f7f22d4f.png)

**Comment by krasa** [comment]
Works fine in 2019.3, if it is the same as Services.

![image](https://user-images.githubusercontent.com/1160875/71327042-b6c95980-2503-11ea-9cb0-b152f6ff0fe9.png)

**Comment by waypoint100** [comment]
yep, looks like it's working in 2019.3, only older versions were affected
