### ISSUE TITLE
Grep Console not appearing in Run/Debug consoles

### ISSUE THREAD

**Issue by steinitz** [krasa/GrepConsole#157]
Thank you for sharing Grep Console.

**Describe the bug**
I've used Grep Console in the past with WebStorm but now it doesn't appear in npm run configurations nor JavaScript Debug run configurations (nor Terminal).

**Environment :**

Grep Console version 9.8.192.4205.1

WebStorm 2019.3
Build #WS-193.5233.80, built on November 25, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
Memory: 1981M
Cores: 8
Registry: ide.windowSystem.autoShowProcessPopup=true, debugger.valueTooltipAutoShow=false, debugger.watches.in.variables=false, ide.tooltip.initialDelay=910
Non-Bundled Plugins: GrepConsole 9.8.192.4205.1, com.alayouni.ansiHighlight, com.intellij.ideolog, izhangzhihao.rainbow.brackets, net.vektah.codeglance, zielu.gittoolbox

I hope this report is useful.

**Comment by krasa** [comment]
Like this? https://github.com/krasa/GrepConsole/issues/155

Screenshot?

**Comment by krasa** [comment]
Need more info.

**Comment by steinitz** [comment]
What more information do you need for this?

**Comment by krasa** [comment]
How does it look like? Isn't the problem that it is a terminal? - https://github.com/krasa/GrepConsole/issues?q=is%3Aissue+is%3Aopen+label%3ATerminalExecutionConsole

**Comment by steinitz-detexian** [comment]
Thanks for your reply.

No, the problem is with the Run and Debug consoles -  the grep console icon and context popup don't appear in Webstorm.  

They haven't appeared for a few years, but I remember when it did.  It was heaven.  I miss it so much.  I do every update, in hope.

**Comment by krasa** [comment]
So like this? #155

**Comment by krasa** [comment]
if it looks like this, then it is a terminal.
![image](https://user-images.githubusercontent.com/1160875/157417838-d1ef6bf9-7e46-44f4-ba57-ef2e3574408d.png)

**Comment by steinitz-detexian** [comment]
Yes, then it's a terminal.  I didn't understand.  Thanks so much for taking the time to clarify.

So much junk in those windows, they're hardly any use.

Thanks again.  All the best.

**Comment by InsOpDe** [comment]
@krasa this means most projects in webstorm wont be compatible with this product since they actually run a terminal, right?

**Comment by krasa** [comment]
Right.

**Comment by inithink** [comment]
How about documenting this?

give it a try! (MacOS shortcuts)

`Shift + Cmd + A(actions) > Registry... > uncheck nodejs.console.use.terminal`


@krasa  How about documenting this?

**Comment by krasa** [comment]
Good idea.

**Comment by LitterSun** [comment]
> How about documenting this?
> 
> give it a try! (MacOS shortcuts)
> 
> `Shift + Cmd + A(actions) > Registry... > uncheck nodejs.console.use.terminal`
> 
> [@krasa](https://github.com/krasa) How about documenting this?

Your method is very effective, thank you, my brother.
