### ISSUE TITLE
Not filter characters after 150

### ISSUE THREAD

**Issue by laixintao** [krasa/GrepConsole#159]
**Describe the bug**
Hi this plugin is good, but I setup a regex like this `.* <<< .*` . The highting works fine, but the filter leave the line after 150 to the console.

Just output any very long log and try to remove it from console.

**Comment by krasa** [comment]
works fine for me.
![image](https://user-images.githubusercontent.com/1160875/77020240-55d6e380-6983-11ea-9906-8741f264cf99.png)
