### ISSUE TITLE
Grep filter icon grayed out in Pycharm 2019

### ISSUE THREAD

**Issue by vincent456** [krasa/GrepConsole#160]
**Describe the bug**
I can't open any grep console in ta python terminal and the icon is grayed out

All I can do is access the settings of the plugin but I can't use it

**Environment :**
PyCharm 2019.3.1 (Professional Edition)
Build #PY-193.5662.61, built on December 18, 2019
Licensed

Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
Registry: 
Non-Bundled Plugins: GrepConsole

**Comment by Trass3r** [comment]
Same in CLion.

**Comment by lblonk** [comment]
Same for me in PyCharm 2019.3.1 (Professional Edition) on Windows

**Comment by krasa** [comment]
If you mean this, then it seems to be a terminal. That is not supported.
![image](https://user-images.githubusercontent.com/1160875/77020107-e3fe9a00-6982-11ea-8912-df8ffce13494.png)

**Comment by fowlerrr** [comment]
For me it looks something like this:

![image](https://user-images.githubusercontent.com/8395358/79444586-4030fa00-7fd3-11ea-9679-5d41bf88b2af.png)


I'm still getting the highlighting (eg. for log messages) but I'm not able to actually _grep_ the logs themselves

**Comment by krasa** [comment]
that is a different issue

**Comment by krasa** [comment]
thanks for the screenshot!

**Comment by krasa** [comment]
@fowlerrr what kind of tests is that? 
It works for me in 2020.1
![image](https://user-images.githubusercontent.com/1160875/79456556-feae4800-7fee-11ea-80d4-3bfd8b2d79f0.png)

**Comment by fowlerrr** [comment]
Actually, I'm using Intellij so it might be a different issue...

IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1944M
Cores: 12
Registry: 
Non-Bundled Plugins: GrepConsole, IdeaVIM, org.jetbrains.plugins.rest, PythonCore, com.github.redfoos.logstash-intellij-plugin, name.kropp.intellij.makefile, no.tornado.tornadofx.idea, org.jetbrains.plugins.hocon, org.vayafulano.relativeLineNumbers

I'll try a quick check on 2020.1 but IIRC it didn't work well with our codebase

**Comment by fowlerrr** [comment]
The same happens with 2020.1:

IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1944M
Cores: 12
Non-Bundled Plugins: IdeaVIM, GrepConsole, org.jetbrains.plugins.hocon, no.tornado.tornadofx.idea, name.kropp.intellij.makefile, org.vayafulano.relativeLineNumbers

**Comment by krasa** [comment]
ok, tell me how to reproduce it :)

**Comment by fowlerrr** [comment]
Wish I could!  For me it's:

- Run test
- Try grep (fails)

It's been very consistent for probably a year.  It happens with anything that's in that output window, whether the test or build logs.

I've only now been bothered enough to raise it.

Maybe it's one of the plugins I have installed?  IdeaVIM?

**Comment by krasa** [comment]
what kind of test? 
what run configuration is that? 
can you gime me the file?

**Comment by fowlerrr** [comment]
Any test will exhibit this behaviour.

For example, this:

```java
import org.junit.Test;

public class AnythingTest {

    @Test
    public void someTest() {
        assert(true);
    }
}
```

Here's the run configuration:

![image](https://user-images.githubusercontent.com/8395358/79463845-42a24c80-7ff1-11ea-8e87-d32c789bbdfa.png)

The only thing I can think there is that we delegate to gradle for the tests.

**Comment by krasa** [comment]
Well Gradle is something completely different. 

Try this https://github.com/krasa/GrepConsole/releases/download/9.11.193.4697.0/GrepConsole.zip

**Comment by fowlerrr** [comment]
Where do they go?

**Comment by krasa** [comment]
drag the whole zip into the editor or
![image](https://user-images.githubusercontent.com/1160875/79468478-4210b280-7fff-11ea-8e2e-519d587792d7.png)

**Comment by fowlerrr** [comment]
Yep.  That one works.  I have grep again!

**Comment by krasa** [comment]
Pycharm issue: https://youtrack.jetbrains.com/issue/PY-41809
