### ISSUE TITLE
Python traceback dump is not colored

### ISSUE THREAD

**Issue by jacopsd** [krasa/GrepConsole#166]
**Describe the bug**
Python traceback dump is not colored

**To Reproduce**
1. Have lines with .\*ERROR.\* case insensitive marked in RED
2. Run a program which logs an ERROR
3. Program also has a python traceback dump containing 'TypeError'

**Expected behavior**
Expect the python traceback dump to be colored red just like the log entries are.

**Screenshots**
See screenshot: log entry ERROR is marked red, but python traceback containing 'TypeError' is not marked red.

![image](https://user-images.githubusercontent.com/210014/79324174-79079b00-7f0f-11ea-968e-dd29b3049da0.png)

**Comment by krasa** [comment]
works for me, post the traceback
![image](https://user-images.githubusercontent.com/1160875/79461196-1e953a00-7ff6-11ea-9c58-c9560e2884b4.png)

**Comment by jacopsd** [comment]
Did you actually cause a type error, or just copy my code?
Difference could be that my type error comes from stderr and the other strings from stdout?

**Comment by krasa** [comment]
still works fine 
![image](https://user-images.githubusercontent.com/1160875/79461862-070a8100-7ff7-11ea-9443-656efbc3c650.png)

**Comment by krasa** [comment]
maybe a particular run configuration behaves differently?

**Comment by jacopsd** [comment]
I just tried it on a different computer with default settings of the plugin, and indeed it works fine there. I will figure out the differences. You can close this ticket. Thank you for your help.
