### ISSUE TITLE
Input filtering on the fly

### ISSUE THREAD

**Issue by diskostu** [krasa/GrepConsole#169]
**Is your feature request related to a problem? Please describe.**
I want to be able to filter an existing console output **on the fly** to only see lines with matching strings.

**Describe the solution you'd like**
The solution could be similar to the Logcat filtering in Android Studio. Often, I'm looking for certain strings in the console output. I can use "Strg +F" to "find" Strings, but still, the console is cluttered. It would be better to only see the lines with the matching String.
Android Studio:
![image](https://user-images.githubusercontent.com/574147/80184764-78f05500-860b-11ea-8ff0-30e22cd04dac.png)

**Describe alternatives you've considered**
Strg + F, but as described above, it could be done better.

Bonus: filtering by log level, on the fly, would be totally awesome. 😀

**Comment by krasa** [comment]
I kinda replicate that in the Grep subtab, having this in the main tab is impossible to do in a plugin, JetBrains would need to implement it.

**Comment by diskostu** [comment]
What is the Grep subtab?Can't find anything like this.

**Comment by diskostu** [comment]
Ah! Found it. Cool, thanks!

**Comment by diskostu** [comment]
A follow up question: is it possible to have more than 1 Grep subtab? Would be super neat.

**Comment by krasa** [comment]
sure

**Comment by diskostu** [comment]
Not necessarily; having multiple subtabs is enough for me.
But I cannot find how to add another subtab. Can you tell me how to do this?

**Comment by krasa** [comment]
the same way as the first one
https://github.com/krasa/GrepConsole/blob/master/screenshotGrepSubConsole.png

**Comment by diskostu** [comment]
Thanks mate :) I think we can close this issue.
