### ISSUE TITLE
"Tail in Console" on big\long files truncate to only last lines 

### ISSUE THREAD

**Issue by victor-h-b** [krasa/GrepConsole#174]
**Describe the bug**
`Tail in Console` on big, long files truncates the beginning of the file and shows only the last lines.

**To Reproduce**
1. Open a big text file (e.g. log file > 4MB) in PyCharm
2. Right-click on the file content and choose 'Tail in Console'
3. Check it In the opened console
4. only the last lines of the file are shown

**Expected behavior**
all the file content is shown

**Comment by krasa** [comment]
That is done intentionally as an optimization, it should display +- what is possible.

Try to change: `File | Settings | Editor | General | Console | Override console cycle buffer size`
 
https://github.com/krasa/GrepConsole/blob/f9495bc1f18732ca5c8e8be7ac00146fb27d82e2/src/krasa/grepconsole/action/OpenFileInConsoleAction.java#L118-L117
(might not work well for UTF-16 and similar encodings).

**Comment by victor-h-b** [comment]
@krasa 
I don't have `Override console cycle buffer size`.
the closest thing I see there is `Console commands history size`:
![console-perfs](https://user-images.githubusercontent.com/54620508/83352584-3978ff00-a355-11ea-8e8a-00af7ed17426.png)

also, when trying to change it to value > 1000, it ignores and set it back to 1000.

my PyCharm version:
> PyCharm 2020.1.1 (Professional Edition)
> Build #PY-201.7223.92, built on April 30, 2020

**Comment by krasa** [comment]
That's strange. 
![image](https://user-images.githubusercontent.com/1160875/83353114-8c03ec80-a350-11ea-881b-fb3a523ff199.png)
```
PyCharm 2020.1.1 (Professional Edition)
Build #PY-201.7223.92, built on April 30, 2020
``

But you can still edit idea.properties at the installation dir. https://stackoverflow.com/a/7836462

**Comment by victor-h-b** [comment]
@krasa 
sorry, it was my stupid mistake. 
previously, I turned this feature off.
anyway, after enable it again, and changing the value it all worked. 
thx
