### ISSUE TITLE
Flutter - Highlight colors not working on IntelliJ

### ISSUE THREAD

**Issue by rohan20** [krasa/GrepConsole#180]
**Describe the bug**
Highlight colors do not work on IntelliJ IDEA Ultimate but they do work on Android Studio.

**To Reproduce**
1. Installed the "Grep Console" plugin on IntelliJ from Preferences.
2. Restart the IDE.
3. Launch the Flutter app.
4. Notice that the logs do not show the background and foreground colors.

**Expected behavior**
The logs on IntelliJ should show the background and foreground colors (as shown on Android Studio)

**Screenshots**
|IntelliJ|Android Studio|
|-|-|
|![image](https://user-images.githubusercontent.com/8232573/96385199-9bb28f00-1192-11eb-9760-f15dab7defcf.png)|![image](https://user-images.githubusercontent.com/8232573/96385206-aa994180-1192-11eb-9777-d3ba89f6186d.png)|

**Environment :**
IntelliJ:
```
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Licensed to Delivery Hero SE / Rohan Taneja
Subscription is active until January 1, 2021
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: AceJump, BrowseWordAtCaret, GrepConsole, String Manipulation, com.bloc.intellij_generator_plugin, net.vektah.codeglance, Dart, andrasferenczi.dart-data-plugin, io.flutter, de.mariushoefler.flutter_enhancement_suite, izhangzhihao.rainbow.brackets
```

Android Studio: 
```
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Dart, GrepConsole, com.google.services.firebase, io.flutter
```

**Comment by Wadeck** [comment]
Same for 2020.2 and 2020.3 EAP (using plugin version 11.1.202.000.0)

**Comment by krasa** [comment]
is it only for tests?

**Comment by sososdk** [comment]
Any update?

**Comment by krasa** [comment]
flutter issue

**Comment by nerder** [comment]
Same issue here

```
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 15, 2020
Licensed to ThoughtWorks, Inc / Stefano Saitta
You have a perpetual fallback license for this version
Subscription is active until November 2, 2021
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: com.github.gitduckhq.intellij-plugin, com.github.leomillon.uuidgenerator, GrepConsole, Lombook Plugin, String Manipulation, com.bloc.intellij_generator_plugin, net.hexar.json2pojo, io.snyk.snyk-intellij-plugin, com.jetbrains.codeWithMe, org.toml.lang, intellij.prettierJS, Dart, io.flutter, org.jetbrains.plugins.vue, org.jetbrains.kotlin, pl.pszklarska.pubversionchecker, Pythonid
````

**Comment by Guang1234567** [comment]
last working version with android studio 4.2 :

https://plugins.jetbrains.com/plugin/7125-grep-console/versions/stable/84802

**Comment by krasa** [comment]
Sorry folks, I used to have a hack that I disabled when IJ changed the way things work in 2020.2, I totally forgot that it ever existed and expected that Flutter will just make a super easy fix... 
Anyways, the hack is back in, hopefully it won't break anything. 
You can update.

**Comment by rohan20** [comment]
Finally! Thank you so much for your work @krasa! 🥇

**Comment by Guang1234567** [comment]
Finally! Thank you so much for your work @krasa! 🥇🥇🥇

hahaha
