### ISSUE TITLE
IDEA2020.3 right click grep show nothing

### ISSUE THREAD

**Issue by baisijian** [krasa/GrepConsole#184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem, do not needlessly crop it (space is free and  e.g. toolwindow title is important).

**Environment :**
 - use a copy button in Help | About dialog

**Additional context**
- Run Configuration: [e.g. JAR Application]

**Comment by krasa** [comment]
Am I supposed to know that is going on from this?
