### ISSUE TITLE
can't delete the grep console tabs

### ISSUE THREAD

**Issue by tadpole145** [krasa/GrepConsole#189]
**Describe the bug**

When I select a keyword as a filter, then right-click and select grep, all logs related to this keyword will be filtered out, but I cannot delete them.

**To Reproduce**
1. select a keyword as a filter
2.  right-click and select grep
3. cannot delete the filter

**Expected behavior**
 

**Screenshots**

![image](https://user-images.githubusercontent.com/35562133/108935504-c6ed4380-7688-11eb-9108-6e204c399a22.png)

**Environment :**
 -IDE version:   idea 2020.1

**Additional context**
- Run Configuration: [e.g. JAR Application]

**Comment by krasa** [comment]
Added a button for it, you can try it: 
[GrepConsole.zip](https://github.com/krasa/GrepConsole/files/6035800/GrepConsole.zip)
![image](https://user-images.githubusercontent.com/1160875/108999088-1d1ab080-76a2-11eb-8538-bb1fa049fb27.png)

**Comment by tadpole145** [comment]
Thank you. this issure was solved.
