### ISSUE TITLE
Ability to Launch "Tail File in Console" as Run/Debug Configuration

### ISSUE THREAD

**Issue by er2** [krasa/GrepConsole#190]
IntelliJ's Compound Run Configuration is extremely useful in allowing me to launch the multiple parts of my application with a single click. Currently I have one that launches

- 2 npm servers
- A tomcat server
- A database running in docker
- an LDAP server running in docker

My build is flaky so sometimes I run into issues running the tomcat server in IntelliJ and resort to launching it via the command line. Then I watch the `catalina.out` log file via the "Tail File In Console" function.

My problem is that "Tail File in Console" doesn't launch as a Run configuration so I can't group it with the above. 

Additionally it is tedious to navigate to the log file every time I use that function, but the fault there lies with either myself or MacOS. Although maybe GrepConsole could remember the last file I selected.

**Comment by krasa** [comment]
Thanks for the donation!

You can try it:
[GrepConsole.zip](https://github.com/krasa/GrepConsole/files/6044556/GrepConsole.zip)
