### ISSUE TITLE
[bug] Can not hightlight the console ouput of Flutter on Android Studio 4.2 which publish on 30 Apr 2021.

### ISSUE THREAD

**Issue by Guang1234567** [krasa/GrepConsole#195]
**Describe the bug**

Can not hightlight the console ouput of Flutter on Android Studio 4.2 which publish on 30 Apr 2021.

**To Reproduce**
1.  install Android Studio 4.2 on macOS
2. install **flutter** plugin
3. install **GrepConsole** plugin
4. create a flutter helloworld project
5. run it
6. see console,  see error (can not hightlight)

**Expected behavior**
Work as Android Studio 4.1.3

Thanks.

**Comment by krasa** [comment]
#180

**Comment by Guang1234567** [comment]
last working version with android studio 4.2 :

https://plugins.jetbrains.com/plugin/7125-grep-console/versions/stable/84802

**Comment by krasa** [comment]
Ok, but it is a flutter issue.

**Comment by krasa** [comment]
Wait, I will try it.

**Comment by krasa** [comment]
It seems that I removed a workaround that flutter needed :(
I do not remember why, I will add it back,

**Comment by Guang1234567** [comment]
@krasa 

thanks your great job, Y(^o^)Y
