### ISSUE TITLE
Folding doesn't seem to work in Java

### ISSUE THREAD

**Issue by chrissyast** [krasa/GrepConsole#201]
**Describe the bug**
Despite the rule I set up finding matching lines, it fails to fold the line. Background colour is shown to demonstrate successful match, but without any highlighting selected it also fails.

NB the folded line shown below was folded through IntelliJ's own UI

**To Reproduce**
Create a rule with the 'fold' box ticked
![image](https://user-images.githubusercontent.com/31564153/135620304-691e9ce2-5ba3-4f65-b0ab-fe809b11b68a.png)

**Expected behavior**
Line shown to be folded

**Environment :**
IntelliJ IDEA 2021.2.1 (Community Edition)
Build #IC-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2022M
Cores: 8
Non-Bundled Plugins: GrepConsole (11.10.211.6086.0)
Kotlin: 212-1.5.10-release-IJ5080.55

**Additional context**
Java console, Spring Boot app

**Comment by krasa** [comment]
Works fine for me, but a rerun is needed.

**Comment by chrissyast** [comment]
@krasa confirmed working after restart. thanks
