### ISSUE TITLE
Possible to use emoij like ✔ inside expressions?

### ISSUE THREAD

**Issue by mmokross** [krasa/GrepConsole#208]
Using GrepConsole for UTF8 encoded log-files I want to highlight lines, which contain emojis like `✔` in the same way as `.*ERROR.*`

Is this possible out of the box - this solution I couldn't find until now - or does this needs a fix?

I tried the following expressions without result
- `.*✔.*`
- `.*\u2714.*`
- `.*\uFE0F.*`

Using GrepConsole 12.1.211.6086.0 with PhpStorm 2021.2.1

**Comment by krasa** [comment]
works fine for me
![image](https://user-images.githubusercontent.com/1160875/148096451-d4e97bb3-2444-4bb7-b346-a7d626ca9cdf.png)

**Comment by mmokross** [comment]
Thank you @krasa I tried again. It's works like a charm. I had mis-configured some definitions before that expression :-(
