### ISSUE TITLE
Exclude seems broken...

### ISSUE THREAD

**Issue by patniemeyer** [krasa/GrepConsole#210]
Is the intent of "Exclude" to invert the match like "grep -v"?  It does not seem to be working.  No matter what I exclude (e.g. a non-existent string) I always get zero output in the grep console.  Thanks.

**Comment by krasa** [comment]
It excludes from what you have already grepped
![image](https://user-images.githubusercontent.com/1160875/153643796-ae277a21-b454-4922-89a7-5ccb36691c35.png)

**Comment by krasa** [comment]
It would probably make sense to grep everything when there are no non-excluding expressions.

**Comment by krasa** [comment]
You can try it (install the whole zip)
[GrepConsole.zip](https://github.com/krasa/GrepConsole/files/8050780/GrepConsole.zip)

**Comment by krasa** [comment]
it was released
