### ISSUE TITLE
instant search

### ISSUE THREAD

**Issue by stefaneicher** [krasa/GrepConsole#212]
can you make an instant search? maybe add an instant search checkbox to select. So that no apply or reload must get pressed

**Comment by krasa** [comment]
You can try it: [GrepConsole.zip](https://github.com/krasa/GrepConsole/files/8099654/GrepConsole.zip)

**Comment by krasa** [comment]
[GrepConsole.zip](https://github.com/krasa/GrepConsole/files/8100595/GrepConsole.zip)

**Comment by krasa** [comment]
it was released.

**Comment by stefaneicher** [comment]
HI,

you were fast. Thanks! I will test it.
Just saw that the history might be polluted a bit.

I search for "test"
the history is:
tes
te
t

**Comment by krasa** [comment]
oh, not sure how to handle that.

**Comment by krasa** [comment]
I have a possible fix, if you want to try it:
[GrepConsole.zip](https://github.com/krasa/GrepConsole/files/8186780/GrepConsole.zip)
