### ISSUE TITLE
Grep console does not clear when source console clears.

### ISSUE THREAD

**Issue by patniemeyer** [krasa/GrepConsole#215]
I'm not certain if you'll consider this a bug or a feature but: I think when the main console clears the derived grep consoles should also clear.  This comes up a lot in Flutter development where you can hit a key to essentially restart the app and this normally clears the main console for you.  I'm not sure how hard this would be for you to detect that clearing but if possible making it an option to follow would be awesome.  

Grep console is awesome and fills such an important hole in Intellij.  Thanks for your work on it.

**Comment by krasa** [comment]
You can try it. I did not test it with flutter...
[GrepConsole.zip](https://github.com/krasa/GrepConsole/files/8134811/GrepConsole.zip)

**Comment by krasa** [comment]
Enable this 
![image](https://user-images.githubusercontent.com/1160875/155583702-aa2d982e-0eed-4026-8c1e-51d7c5e5edb9.png)

**Comment by patniemeyer** [comment]
It works!  You rock.  Thanks.
