### ISSUE TITLE
Grep console not working in GoLand 2022.2.4

### ISSUE THREAD

**Issue by leesings** [krasa/GrepConsole#248]
**Describe the bug**
There is no grep configuration option to run the golang program，and grep not working

**To Reproduce**
1. Run Go application
2. Console no grep setting tab

**Expected behavior**
grep setting tab need show 

**Screenshots**
There is no grep configuration option to run the program，and grep not working
console left:
![image](https://user-images.githubusercontent.com/43227866/204848177-2a4dd3e8-65b6-4809-b5d0-a6e8c1ba0e1b.png)
console right:
![image](https://user-images.githubusercontent.com/43227866/204850174-dc4b87c7-637a-4f5d-9d7a-86e0bad93478.png)

**Comment by aimook** [comment]
I have the same problem too.

**Comment by lqxhub** [comment]
I have the same problem too.

**Comment by krasa** [comment]
https://github.com/krasa/GrepConsole/issues/175

**Comment by lqxhub** [comment]
> #175

successfully solved the problem,thank you so much

**Comment by leesings** [comment]
> #175

thank you so much
