### ISSUE TITLE
get surrounding information

### ISSUE THREAD

**Issue by axaluss** [krasa/GrepConsole#254]
**Is your feature request related to a problem? Please describe.**

Oftentimes when looking at logs, important information is contained in the lines around stuff I grepped, but not in the line itself. 

For example I'd like to see the complete stack trace in the grep log.

Or there is some log that's producing a multi line list.

Or there is a log line that's easy to grep, but the actually interesting info is hard to grep and in the lines before

**Describe the solution you'd like**

**jump to origin**

In the grep log window, have a button, context menu or sth, which lets me jump to the original line of the matched line.

**grep surrounding option** 

For each grep statement, let me choose the number of lines before and after to include in the grep.

This could also be combined with the option to include/exclude filter those surrounding lines.

**Comment by krasa** [comment]
surrounding option is already there 
![image](https://user-images.githubusercontent.com/1160875/217832011-e9427edb-888d-4633-b559-6d8d342921ad.png)

**Comment by piotr-dobrogost** [comment]
I think this issue could be closed.
