### ISSUE TITLE
truncate a log file, no display in console

### ISSUE THREAD

**Issue by Noctune** [krasa/GrepConsole#256]
**Describe the bug**
truncate a log file, no display in console.

**To Reproduce**
1. tail a log file like debug.log, use "echo 123 >> debug.log" to append line, the console displays the new line.
2. use "echo 234 > debug.log" to clear the file and write a new line, the console display nothing.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/60099362/220574239-384f2509-c6f5-4855-8cca-b213f076c50e.png)

**Environment :**
 - PyCharm 2022.3.2 (Community Edition)
Build #PC-223.8617.48, built on January 24, 2023

**Additional context**
- Run Configuration: default

**Comment by ipcoder** [comment]
I am suffering from the same problem.
Is not updated when log file is renewed.

**Comment by krasa** [comment]
You can update and try it. Not sure if checking size is enough https://github.com/krasa/GrepConsole/commit/b5cab50ced1fe580d6db7ddb16b83d3edbcb9e74#diff-25596291a6d37824df6f5556dc0b2e14e9b9c9f7e73c88bdbabc9b37422ebe0cR135

**Comment by ipcoder** [comment]
Thank you for this quick fix!
It works in most the cases, so this solution is quite acceptable.

The only thing is that it keeps the portion of the log before the truncation. Is it possible to clear it from the console, 
and keep only the lines coming after the truncation?

Thanks

**Comment by krasa** [comment]
Done :-)

**Comment by ipcoder** [comment]
Brilliant! Thanks
