### ISSUE TITLE
Entering search terms does not update filtered result immediately

### ISSUE THREAD

**Issue by rillig** [krasa/GrepConsole#271]
**Describe the bug**
As a new user of GrepConsole, I played around with the Grep view of the console and found that it doesn't feel like the rest of the IDE.

* Editing the search text does not immediately update the filtered console text. To do that, I have to click the Reload button.
    * That button is missing a keyboard shortcut.
    * That button is about 50 cm away from the search field, which is a long way to travel with the mouse.
* GrepConsole doesn't remember the search options, for example that I want to search for regular expressions.
* Clicking 'Apply' has no intuitive effect. This button should have a tooltip explaining what it does, or if that action can be done in the background, the button should be replaced with a background action.
* Modifying the search options (Case, Word, Regex) immediately updates the filtered result, contrary to editing the search term.
* Even when the filtered result is nonempty, the text to the left of the search field shows `0/0`.

**To Reproduce**
1. Run a program, to get a console view.
2. From the context menu of the console view, select 'Grep'.
3. Type a few characters in the search field.
4. Toggle the search options.
5. Close the Grep view and open another one.

![image](https://github.com/krasa/GrepConsole/assets/3233724/c09bc2e3-0f31-4ff5-a072-603073a72daa)

**Expected behavior**
* Step 3 updates the filtered view.
* Step 5 remembers the previous search options.

**Environment :**
CLion 2023.2 EAP 2

**Comment by rillig** [comment]
While pressing Enter is more intuitive than pressing Alt+X twice, it's not quite what I meant. I meant that with every key press, the search result should update. And if the search result is the same as before, nothing should flicker.

The two other issues that I had reported now work nicely and make the Grep Console feel more like an integral part of IntelliJ.

**Comment by krasa** [comment]
You can enable it by ctrl+click on the reload button.
