### ISSUE TITLE
Persist (or pin) Grep Funnel Tabs Between IntelliJ Sessions

### ISSUE THREAD

**Issue by kvenn** [krasa/GrepConsole#283]
**Is your feature request related to a problem? Please describe.**
I have certain filters I want to persist per-project.

Ex: I have "analytics" logs and "operation" logs that my mobile app emits. I'd like to have a tab for each every time I open that project.

**Describe the solution you'd like**
The tabs with the filters stay pinned in the browse across restarts.

**Describe alternatives you've considered**
None

**Additional context**
I need to do this every time. I'd love if the tab was just always there.

<img width="361" alt="image" src="https://github.com/krasa/GrepConsole/assets/1782467/bfa827d2-7184-4433-947c-f2995d56ab82">

![image](https://github.com/krasa/GrepConsole/assets/1782467/64249287-c474-4de6-a735-e4ea92e868ba)

Great plugin, by the way. Thank you!!

**Comment by krasa** [comment]
Is this selected?
![image](https://github.com/krasa/GrepConsole/assets/1160875/bdf664fa-3e75-4e6a-a7a9-b82decb323b4)

Pins are persisted, it may be broken for a particular Run Configuration type.  Which one?
![image](https://github.com/krasa/GrepConsole/assets/1160875/1c3fb684-7613-4962-b80a-a232ec470d7b)

**Comment by krasa** [comment]
Flutter plugin uses the console in some weird way, I will have to check.

**Comment by kvenn** [comment]
Incredible, thank you 🙏 Let me know if I can help.

**Comment by krasa** [comment]
fixed with #282
