### ISSUE TITLE
ANSII coloring doesn't work anymore in IDEA 14 (works in IDEA 13).

### ISSUE THREAD

**Issue by vic64** [krasa/GrepConsole#39]

**Comment by nekosaur** [comment]
So IntelliJ 14 now strips away all ANSI codes and uses their internal coloring as seen in the screenshot above? Does that mean GrepConsole can no longer be used for control codes such as clear screen, bold, underline, and so on?

**Comment by krasa** [comment]
Correct.

**Comment by piotr-dobrogost** [comment]
@krasa 
> It seems that IntelliJ "supports" ANSI now...

Why is the word *supports* quoted?
Is there something wrong with this support?
