### ISSUE TITLE
ANSI colors

### ISSUE THREAD

**Issue by jahsen** [krasa/GrepConsole#42]
Question?
Is it possible Grep console to use the coloring scheme for the terminal (or to be configured)?
Thanks

**Comment by piotr-dobrogost** [comment]
Have you seen issue #39?

**Comment by jahsen** [comment]
Yes, I am with PHPStorm but strangely enough the IDE does not respect the custom colors that I did set!

**Comment by krasa** [comment]
Afaik terminal implementation has nothing to do with console, that is a reason why Grep Console does not work with terminal at all, and why ANSI (currently handled only by jetbrains) may work differently - you need to create an issue on jetbrains tracker.

**Comment by jahsen** [comment]
Thank you very much :) :+1:
