### ISSUE TITLE
Standard output and standard error are mixed up (not synchronous)

### ISSUE THREAD

**Issue by dergo** [krasa/GrepConsole#43]
When Grep Console plugin is enabled, standard output and standard error are mixed up (not synchronous).

For example, the following program:
```python
for i in range(1, 51):
    print "line", i

undefined()
```
should print "line 1" to "line 50" then show an error message about the undefined method.
Instead the error message is mixed up in the "line i" messages.

Example of output:
```
/usr/bin/python2.7 .../test.py
line 1
line 2
Traceback (most recent call last):
line 3
line 4
...
line 24
line 25
  File ".../test.py", line 4, in <module>
line 26
line 27
    undefined()
line 28
line 29
line 30
line 31
line 32
NameError: name 'undefined' is not defined
line 33
line 34
...
line 49
line 50

Process finished with exit code 1
```

**Comment by krasa** [comment]
you are right, but they are mixed up even without the plugin :-) Nothing we can do about that.

**Comment by dergo** [comment]
Oops, indeed :)
I tried yesterday and it was not mixed up without the plugin, but I just retried now and you're right, sometimes it's also mixed up.
I close the issue.

**Comment by piotr-dobrogost** [comment]
For furhter information see [Save stdout, stderr and stdout+stderr synchronously](http://stackoverflow.com/q/4497817/95735).

> But some people won't accept either the loss of separation between stdout and stderr, or the desynchronization of lines. They are purists, and so they ask for the most difficult form of all -- I want to log stdout and stderr together into a single file, BUT I also want them to maintain their original, separate destinations.
