### ISSUE TITLE
On Windows, "match whole line" matches the whole line and subsequent lines

### ISSUE THREAD

**Issue by lowjoel** [krasa/GrepConsole#45]
![untitled](https://cloud.githubusercontent.com/assets/2505070/7739468/fd2805c4-ff93-11e4-835f-c589063a679f.png)

Possibly due to `\r\n` vs `\n`?

**Comment by krasa** [comment]
maybe you have enabled "Enable multiline output" checkbox?
![image](https://cloud.githubusercontent.com/assets/1160875/7935511/e3b9de58-0931-11e5-8f08-02d8fd00315e.png)

**Comment by lowjoel** [comment]
Wow, thanks. I did not notice that checkbox. Sorry for the noise!
