### ISSUE TITLE
No way to disable the beep while tailing

### ISSUE THREAD

**Issue by KarolS** [krasa/GrepConsole#48]
The Tail File feature plays an annoying sound regardless of any other configuration.

Grep Console 5.8.134.1007
IntelliJ IDEA 14.1.3 build IC141-1010

**Comment by krasa** [comment]
you could configure playing of sounds when some text matches a pattern, try to not configure such things, or try to reset settings to to default
![image](https://cloud.githubusercontent.com/assets/1160875/8192828/3bc267ba-1471-11e5-8998-4a47b1689577.png)

**Comment by KarolS** [comment]
I have no sounds enabled in the configuration. 

I have reset the settings to default, but the problem persists.

**Comment by krasa** [comment]
Totally strange, perhaps some OS feature? To be totally sure, I could perhaps made a build which does  not contain the player...

**Comment by krasa** [comment]
Does it also happen when you run an application which will periodically print something to log, and also debug an application, so that you have also 2 active panels but without the tail?

**Comment by KarolS** [comment]
No, having both Run and Debug causes no problems. It's only the Tail panel.

**Comment by krasa** [comment]
Please try to install this https://www.dropbox.com/s/ncvpv0vqfvo6e5i/GrepConsole.zip?dl=0

**Comment by KarolS** [comment]
Doesn't help. Beeps happen in the same circumstances: a tailed file rapidly fills while the Run panel is active, with the app running in it.

**Comment by krasa** [comment]
Which OS do you have?

**Comment by KarolS** [comment]
Windows 7. 

I'll test it on Linux on the weekend.

**Comment by krasa** [comment]
I work with Win 7 on 2 machines myself. Try to go to control panels | Sound | and switch to No Sound scheme.

**Comment by KarolS** [comment]
I've been using No sound scheme since forever. Just checked, it's still unchanged.

**Comment by KarolS** [comment]
And no unexpected sounds on Linux on the stock GrepConsole.

**Comment by krasa** [comment]
have you tried stock intellij on windows with only GrepConsole?
