### ISSUE TITLE
run grepConsole per configuration

### ISSUE THREAD

**Issue by bobwenx** [krasa/GrepConsole#50]
Current grepConsole act as global console plugin. when i change some settings, it apply to all run/debug configuration profile. 
It's possible to provide per configuration profile?
eg: when i `debug` some configuration profile, i want to setting specified color for logging. but i should be able to switch to another color settings when i `run` the configuration profile(the grepConsole will switch it automatically according to current context).

**Comment by krasa** [comment]
i don't know a way how to do it right now...

**Comment by bobwenx** [comment]
how about implements configuration profile run hook? (like Run Launch)

![image](https://cloud.githubusercontent.com/assets/2533748/8471437/d9e46230-20ca-11e5-9c70-f04d3b057f32.png)

the `grepConsole` settings will change when hook call it.

**Comment by krasa** [comment]
Done, feel free to test it, before releasing, if you want.
https://github.com/krasa/GrepConsole/releases/download/7.0.162.000.0/GrepConsole.zip
