### ISSUE TITLE
Filter out doesn't remove the lines, but just blanks them, on IDEA 15

### ISSUE THREAD

**Issue by KarolS** [krasa/GrepConsole#55]
GrepConsole 5.8.134.1007
IntelliJ IDEA 15.0 build 143.381

It worked okay on 14.

##### Program output:

    A
    B
    C

##### GrepConsole filters:

* Expression: B  
* Filter out: yes  
* Whole line: no/yes (tried both)
* Continue matching: no

##### Expected output:

    A
    C

##### Actual output:

    A
    
    C

**Comment by krasa** [comment]
works fine for me on 15.0.2 EAP 
![image](https://cloud.githubusercontent.com/assets/1160875/11289515/fe81755c-8f2d-11e5-8994-3164c3fa97d7.png)

**Comment by KarolS** [comment]
So it's even more weird than that: The problem only exists in the output of *tests*. The console that is used when you launch the program works fine, I wrote a similar example of a Main class and it gave the correct output.

Here's how it looks like in the test panel:

![](http://i.imgur.com/xxSUdFv.png)

The blank lines, as you can guess, are some random cruft spouted out to the stdout by Eclipselink.

**Comment by krasa** [comment]
Thanks, I will dig in IJ source...

**Comment by krasa** [comment]
Cannot reproduce it in IJ 16 EAP, they probably fixed it...

**Comment by Nohus** [comment]
This issue happens for me in IDEA 2017.1.2, plugin 7.10.
Works after I downgraded the plugin 6.8.

**Comment by krasa** [comment]
@Nohus still can't reproduce.
Post a screenshot and OS.
![image](https://user-images.githubusercontent.com/1160875/32349343-03c7b956-c017-11e7-8e51-fc0b54a55d07.png)

**Comment by krasa** [comment]
Ok, I reproduced it for JUnit tests.

**Comment by krasa** [comment]
@Nohus it behaves the same for me with  6.8.

**Comment by Nohus** [comment]
OS is Debian 9.2 (stretch), I see you reproduced it now anyway though.

**Comment by gerardcanal** [comment]
I am having this issue in CLion. The output is not seen and filtered, but a blank line is pushed to the console. Is there any workaround?
Using Ubuntu, last Clion version 2019.1

**Comment by krasa** [comment]
I will need more information, an example project would be the best.

**Comment by gerardcanal** [comment]
Hi!
I can't provide the whole project, but it's related to this: https://github.com/ros/ros_comm/issues/1370 
Basically, when debugging ros programs I keep getting these lines with "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call". I'm fine with just filtering that out with GrepConsole.

Those are my settings (I disabled the line in order to show it in the screenshot):  
![image](https://user-images.githubusercontent.com/5610438/56432390-6abb7a80-62cd-11e9-9e72-c3ec274a8377.png)

The filter expression is `.*poll failed with error Interrupted system call.*`, and with it, the text does not appear but an empty line is shown. Not sure if those error messages are printed through stdout or sterr, and they use some ANSI colors when printing them.

**Comment by krasa** [comment]
And what kind or Run Configuration? 
![image](https://user-images.githubusercontent.com/1160875/56433403-11554a80-62d1-11e9-8dc6-16f9207feb92.png)

**Comment by gerardcanal** [comment]
Nothing special there, didn't changed any option:
![image](https://user-images.githubusercontent.com/5610438/56433697-0ea72500-62d2-11e9-8627-dcd9a4eec034.png)

**Comment by krasa** [comment]
I reproduced only an entirely different problem - text is not filtered at all if there is no sleep between printing.


Could you try if this:
```
#include <iostream>
#include <unistd.h>

int main() {
    std::cerr << "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call" << std::endl;
    usleep(5000);
    std::cerr << "xxxx" << std::endl;
    usleep(5000);
    fprintf(stdout, "[xxx\n");
    std::cerr << "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call" << std::endl;
    usleep(5000);
    fprintf(stdout, "[xxx\n");
    std::cerr << "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call" << std::endl;
    usleep(5000);
    std::cerr << "xxxx" << std::endl;
    usleep(5000);
    std::cerr << "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call" << std::endl;
    usleep(5000);
    fprintf(stdout, "[xxx\n");
    usleep(5000);
    fprintf(stderr, "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call\n");
    usleep(5000);
    usleep(5000);
    fprintf(stderr, "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call\n");
    usleep(5000);
    fprintf(stderr, "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call\n");
    usleep(5000);
    fprintf(stderr, "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call\n");
    usleep(5000);
    fprintf(stderr, "[ERROR] [1555689699.635627747]: poll failed with error Interrupted system call\n");
    return 0;
}
```
results in this?

![image](https://user-images.githubusercontent.com/1160875/56446090-e551bd80-6300-11e9-8244-8fcd2a9e66ec.png)

**Comment by krasa** [comment]
Ok I reproduced it, it is quite random for me, and it is probably because the IDE does not wait for a line break.
I will add a checkbox to workaround it.

**Comment by gerardcanal** [comment]
Hi krasa!
Indeed, I have the same result. Even without the sleeps, it filters correctly... But it doesn't when using the ros logging macros (which are the ones that generate that kind of error):
![image](https://user-images.githubusercontent.com/5610438/56456121-25985680-6368-11e9-9bf6-7fd45c10813a.png)

I think (but not 100% sure) that the printing method used by the macro is this one: https://github.com/ros/rosconsole/blob/ba4e1ae06b5bce3039ac5d20853248b51198e431/src/rosconsole/rosconsole.cpp#L336

**Comment by krasa** [comment]
try this: [GrepConsole.zip](https://github.com/krasa/GrepConsole/files/3100047/GrepConsole.zip)

**Comment by gerardcanal** [comment]
This one seems to fix it! 
Thank you so much! It was quite painful to debug with so many [ERROR] messages in the terminal!
