### ISSUE TITLE
Color picker doesn't work (IntelliJ 2016.1.2)

### ISSUE THREAD

**Issue by fsomers** [krasa/GrepConsole#56]
I tried using the Choose Color / "color picker" option to select a foreground color for a pattern.

A black square is displayed, instead of the magnifier option I would expect for picking a color, making it quite difficult to select colors that aren't large areas.

**Comment by krasa** [comment]
screenshot?

**Comment by fsomers** [comment]
<img width="1920" alt="screen shot 2016-05-17 at 08 31 55" src="https://cloud.githubusercontent.com/assets/16169/15314504/3225d5c4-1c0a-11e6-82d4-8e7f5bd3f357.png">

**Comment by krasa** [comment]
That is entirely IntelliJ platform thing. I am pretty sure you would see the same thing with in Editor Colors settings. So I would recommend to report bug to JetBrains.
And btw it works for me on WIn 7 fine in 2016.2 EAP.

**Comment by fsomers** [comment]
Fair enough; done.
