### ISSUE TITLE
File path in tooltips of tabs

### ISSUE THREAD

**Issue by macino** [krasa/GrepConsole#57]
It'd be nice to have a tooltip showing the file path. If I've a few logs open, I get confused where to look especialy, when their names are just timestamps. Even judging by the content is a bitdifficult, when I have a few php jobs producing similar logs.

Thanks.

**Comment by krasa** [comment]
Where have you seen such thing? Because it is not like I can change core IntelliJ bahaviour...

**Comment by macino** [comment]
Hi, The editors tabs have tool tips, also the tabs in database console. I didn't look for the current api, but I assume the feature is available as the DB console is also a plugin.

**Comment by krasa** [comment]
that's different components, this api does not support it. 
All I could do is make a dialog where you could choose a tab name.

**Comment by macino** [comment]
Ok, then I think you can close this issue. Something else is imho quite not as fast and flexible. Although thank you for this plugin. :)

**Comment by krasa** [comment]
You're welcome
