### ISSUE TITLE
Ability to live-filter console content

### ISSUE THREAD

**Issue by StanAccy** [krasa/GrepConsole#58]
Your plugin is awesomely helpful when debugging / monitoring programs.  However, when debugging multi-threaded programs, it would be really helpful if I could live-filter the contents (non-destructively) to only show lines that contained a certain regex ( in my case Id use the thread name or threadId).  Then I could focus in on one specific thread without all the noise of the log lines from other threads.  Think of it as a live 'grep' functionality.  I dont need it to work as the console is scrolling with new text (although that would be nice), but if I could filter out lines I dont want to see after a program ran and just work with the text in the console buffer it would be great.

**Comment by krasa** [comment]
I tried to implement it some time ago, but IntelliJ API did not support it - I wanted to open a new filtered console Tab, but there was no sane way how to get a reference I needed. 
But perhaps opening a new frame would be enough.

**Comment by krasa** [comment]
Prototype will be ready soon

![image](https://cloud.githubusercontent.com/assets/1160875/17874404/bd7173aa-68cb-11e6-9c1b-32be6964001f.png)


![image](https://cloud.githubusercontent.com/assets/1160875/17874357/6e5d4cb2-68cb-11e6-8821-3286ea887a52.png)

**Comment by krasa** [comment]
Done.
