### ISSUE TITLE
Allow hyperlink lines referring to filename:line number (error lines)

### ISSUE THREAD

**Issue by ssbarnea** [krasa/GrepConsole#59]
Imagine that you have these in the console:
```
/usr/local/bin/flake8
./wstools/TimeoutSocket.py:51:13: F821 undefined name 'apply'
./wstools/TimeoutSocket.py:68:21: F821 undefined name 'apply'
./wstools/UserTuple.py:57:32: E721 do not compare types, use 'isinstance()'
```
The user should be able to click on this line in order to open the file at the correct line (2nd parameter is the column number but this is optional, only some tools do report a column number).

The pattern is kinda universal as most compilers and linters to use the same syntax.

**Comment by krasa** [comment]
Awesome Console plugin does that, or something similar.

**Comment by ssbarnea** [comment]
Thanks! It seems that JenBrains did a pretty good job from making the plugin installation as confusing as it can be. I had to look for 10 minutes in the multiple lists of plugins....

**Comment by ssbarnea** [comment]
It seems that I ended up raising a bug against the not-yet-very-awesome-console plugin.
https://github.com/anthraxx/intellij-awesome-console/issues/18
