### ISSUE TITLE
Bright black (1;30) is the same as dim white (37)

### ISSUE THREAD

**Issue by TWiStErRob** [krasa/GrepConsole#60]
There are 4 grayscale colors in ANSI:
- dim black: `30` (0% white)
- bright black `1;30` (~25% white)
- dim white `37` (~75% white)
- bright white `1;37` (100% white)

Grep console is missing "bright black"; here's how it looks like in IDEA console:
![image](https://cloud.githubusercontent.com/assets/2906988/17277808/aaf8c470-574c-11e6-9d24-e70c2ded8617.png)

Here are the unhidden escapes:
![image](https://cloud.githubusercontent.com/assets/2906988/17277810/be5818d6-574c-11e6-805b-eb93470122db.png)

Here's how it should look like (from Windows 10 cmd; native or ANSICON, not sure):
![image](https://cloud.githubusercontent.com/assets/2906988/17277813/e35cdefa-574c-11e6-9ad6-adcd3a83ee2b.png)

Notice that in IDEA `DEBUG` and `debug` has the same color, while in the terminal they are 2 distinct colors.

I'm using a `log4j2.xml` equivalent to this:

``` xml
<Configuration strict="true">
    <Properties />
    <ThresholdFilter level="TRACE" onMatch="neutral" onMismatch="deny" />
    <Appenders>
        <Appender type="Console" name="color-console">
            <Layout type="PatternLayout" pattern="%highlight{%date{ISO8601} %-5level}{FATAL=bright magenta, ERROR=bright red, WARN=bright yellow, INFO=dim white, DEBUG=bright black, TRACE=cyan} %style{%message}{bright,white}%n" />
        </Appender>
    </Appenders>
    <Loggers>
        <Root level="ALL">
            <AppenderRef ref="color-console" />
        </Root>
    </Loggers>
</Configuration>
```

**Comment by krasa** [comment]
ANSI is no longer supported by this plugin, IntelliJ itself does it instead.
