### ISSUE TITLE
Bold attribute shoudn't be applied to background color

### ISSUE THREAD

**Issue by TWiStErRob** [krasa/GrepConsole#61]
`41;37;1` should be bright white text on dark red background.

Source: https://www.google.com/search?q=ansi+colors&tbm=isch
Notice that none of the images have actual bright backgrounds, most of the matrices are 8x16.
Whenever the BG is bright, it's a color scheme, or a non-ANSI (Windows, Python, etc.) terminal.

**Comment by TWiStErRob** [comment]
Source: https://www.google.com/search?q=ansi+colors&tbm=isch
Notice that none of the images has actualy bright backgrounds, most of the matrices are 8x16.
Whenever the BG is bright, it's a color scheme, or a non-ANSI (Windows, Python, etc.) terminal

**Comment by krasa** [comment]
ANSI is no longer supported by this plugin, IntelliJ itself does it instead.
