### ISSUE TITLE
Use color configuration of IDEA's ANSI color scheme

### ISSUE THREAD

**Issue by TWiStErRob** [krasa/GrepConsole#62]
These settings exist:
![image](https://cloud.githubusercontent.com/assets/2906988/17278020/c2af57a0-5751-11e6-88fc-48d926168382.png)

They are used in: p:\tools\ide\idea\lib\idea.jar!com/intellij/openapi/options/colors/pages/ANSIColoredConsoleColorsPage.class

**Comment by TWiStErRob** [comment]
Huh, yeah, I was wondering why it wasn't working, and why I needed to install this plugin. It's with AppEngine. I'll open a YouTrack issue.

I hope you don't mean Grep Console is deprecated, because the regex based highlight feature is really nice.

**Comment by krasa** [comment]
Just ANSI part is deprecated, everything else is still useful!

**Comment by TWiStErRob** [comment]
https://youtrack.jetbrains.com/issue/IDEA-159465
