### ISSUE TITLE
support for multiple profiles?

### ISSUE THREAD

**Issue by end-user** [krasa/GrepConsole#67]
I see that the plugin saves its setting under `%userprofile%\{IntelliJversion}\config\options\GrepConsole.xml`.  The xml file appears to have a list of profiles.  Would it be possible to save multiple profiles with different configurations?

**Comment by krasa** [comment]
I have not implemented a gui for it, but it should be easy, just few buttons, and maybe dropdown choice. Pull request welcomed.

**Comment by krasa** [comment]
Done, feel free to test it, before releasing, if you want.
https://github.com/krasa/GrepConsole/releases/download/7.0.162.000.0/GrepConsole.zip
