### ISSUE TITLE
How to filter out lines that doesn't match a regex

### ISSUE THREAD

**Issue by tribbloid** [krasa/GrepConsole#70]
I've tried
[.*INFO.*] in 'Unless Expression' and tick 'filter out' but nothing happens. All the lines contains INFO are still there.

The highlight works though.

Thanks a lot for help.

Yours Peng

**Comment by krasa** [comment]
this will filter anything but INFO lines:
![image](https://cloud.githubusercontent.com/assets/1160875/22628364/1be08a22-ebd3-11e6-9c22-8cbe7fc61ff1.png)
