### ISSUE TITLE
"Filter out" resolves to blank line

### ISSUE THREAD

**Issue by klassm** [krasa/GrepConsole#71]
Hi,
when adding some expression with only "filter out" set, the filtered text will disappear from console, but a blank line will stay.
Matthias

**Comment by krasa** [comment]
ide version?

**Comment by klassm** [comment]
IU 2016.3

**Comment by krasa** [comment]
2017.1 seems to work fine. Jetbrains were doing some big changes to the console...

**Comment by klassm** [comment]
Ok, then I'll wait for 2017.1. Thanks for looking after this issue!
