### ISSUE TITLE
Grep Console filter out LLDB

### ISSUE THREAD

**Issue by topeerz** [krasa/GrepConsole#72]
When applying Grep Console filtering to output with last rule filtering out everything not matched so far I am not able to use lldb. I need some way to enable filtering for console while NOT filtering lldb output.

**Comment by krasa** [comment]
Why?

**Comment by topeerz** [comment]
Well I am working on large app which logs ton of things on console. When I am working on particular feature I am interested on live-grep when I am filtering out all stuff not related - so I am filtering logs by feature tag (which is included in log). At the same time when I put breakpoint in code I want to be able to evaluate some lldb exp. To do it now I need each time to turn off grep console eval lldb and than turn grep console back. This is quite annoying.

**Comment by krasa** [comment]
Do I understand it right, that you want 'Filter out' to work only on the main console, not on live-grep ones?

**Comment by topeerz** [comment]
Yes, I want to filter on main console only and have lldb console intact (I
am not sure how you define live-grep console in this case I just don't
wan't lldb console to be affected at all).

**Comment by krasa** [comment]
That makes sense. I will see what I can do.

**Comment by krasa** [comment]
Wait, are we talking about the same thing? 

Do you have 2 consoles to begin with or are you using Grep context button?
