### ISSUE TITLE
Hangs with high CPU usage

### ISSUE THREAD

**Issue by ice-pro** [krasa/GrepConsole#73]
After running some tests it hangs with high CPU usage.
At first, I've started the discussion with JetBrains here https://youtrack.jetbrains.com/issue/IDEA-167540.
But it seems that they are already aware of this problem.

Do you know the reason? Is it a bug or it was caused by configuration (the rules I have are pretty simple)?
What info do you need for analysis?

**Comment by krasa** [comment]
Do you have enabled "Match only first N characters on each line:" with some reasonable value?

**Comment by krasa** [comment]
It should be fixed now.

**Comment by ice-pro** [comment]
Cool. Unfortunately, I cannot check it now, so if you want we can keep it open for some time (I believe in a week I will be able to check it) or we can close it and later I will create a new one if needed.

**Comment by krasa** [comment]
that's fine, we can keep it open.

**Comment by ice-pro** [comment]
tested, it works!
thank you for help and quick resolution!
