### ISSUE TITLE
Add possibility to save the Tail files when close PHPStorm and open the files when reopen.

### ISSUE THREAD

**Issue by oscarmolinadev** [krasa/GrepConsole#74]
Add possibility to save the files when close PHPStorm and open the files when reopen. Also a button for clear all files open.

**Comment by krasa** [comment]
you mean for Tail?

**Comment by oscarmolinadev** [comment]
Yes :)

**Comment by krasa** [comment]
The only problem is that I am unable to detect if they were closed by a middle mouse button click on the tab...

**Comment by krasa** [comment]
I have made it per project,  sounds good?

**Comment by oscarmolinadev** [comment]
Yes perfect! big thanks!

**Comment by krasa** [comment]
done

**Comment by oscarmolinadev** [comment]
Hi @krasa don't work for me.

![image](https://cloud.githubusercontent.com/assets/6513086/22763862/94455678-ee67-11e6-8ccb-83cfa0702b2a.png)

I closed the PHPStorm and reopened and it does not show me tail or pin tabs.

**Comment by krasa** [comment]
That is a different button :-) Use that one on the left

**Comment by oscarmolinadev** [comment]
Right my fault! works perfect :)
