### ISSUE TITLE
Make GrepConsole work for text scratch buffers and text files

### ISSUE THREAD

**Issue by vertex-github** [krasa/GrepConsole#76]
Grep console is awesome and we use it constantly.  The ability to highlight different work flows / threads etc within console output is extremely valuable.  We'd love to be able to use the same highlight functionality for viewing text files (both stored on disk and in scratch buffers).  This would let us highlight and analyze application logs offline.

**Comment by krasa** [comment]
Tools | Grep Highlight Editor

**Comment by vertex-github** [comment]
Oh, I never realized!  That's awesome!
