### ISSUE TITLE
Add possibility to open a line of tail in new window for analyze. 

### ISSUE THREAD

**Issue by oscarmolinadev** [krasa/GrepConsole#77]
Add possibility to open a line of tail in new window for analyze. For example CTRL+ Double Click on a line and open in window or something like that.

![image](https://cloud.githubusercontent.com/assets/6513086/22728159/b4df3056-eddc-11e6-99ed-1ec6c58be02e.png)

Thanks!

**Comment by krasa** [comment]
You mean like open it in a scratch file?

**Comment by oscarmolinadev** [comment]
Yes

**Comment by krasa** [comment]
Not sure if ctrl+click is feasible, but a context button should be  - in all consoles, not only for tail.

**Comment by oscarmolinadev** [comment]
ctrl + click was an example, for me the best thing is that it can be configured in settings  if it is possible (keys configured + click) and I agree too about context button.

**Comment by krasa** [comment]
I found out that you can already press ctrl+alt+shift+insert or whatever you have for Main menu | File | New | Scratch File :-)

**Comment by krasa** [comment]
and I meant that I didn't know if I can detect the click event

**Comment by oscarmolinadev** [comment]
I hope you can! I have really big lines in the logs and for analyze is a nightmare in tail :(

**Comment by krasa** [comment]
So just select it and press ctrl+alt+shift+insert
