### ISSUE TITLE
Add flag to enable multiline filtering

### ISSUE THREAD

**Issue by oyvindBjerke** [krasa/GrepConsole#79]
There is currently a feature to enable/disable multiline highlightning. But no flag to enable/disable multiline filtering.

Say I am filtering away trace and debug log statements, when a statement spans several lines only the first line is filtered.

**Comment by krasa** [comment]
I will add it, but you would be better of customizing your logger to print the level on all lines.

**Comment by ursusursus** [comment]
I'm sorry but how do I use this? I select some string in the console, right click, Grep. Now I have a new tab with only the given keyword.

But it still is singleline, if the message is multiline then it is clipped

**Comment by krasa** [comment]
This was about Filtering, not Grepping.
For Grep there is only this:
![image](https://user-images.githubusercontent.com/1160875/190000633-3243d121-dd42-455b-b3fe-3bed54d622cc.png)
