### ISSUE TITLE
Option to Not Grep Files (Console Only)

### ISSUE THREAD

**Issue by Mochnant** [krasa/GrepConsole#81]
It doesn't seem like there is a way to disable Grep Console for open files in the editor, while allowing it to modify the console.  Is this possible, or might such a flag be added?  For those of us with no need to grep files it would seem like a performance improvement.

**Comment by krasa** [comment]
Why would you need to disable it for the editor, when it is not doing anything to the editor until you click on "Grep Highlight Editor" action.

**Comment by Mochnant** [comment]
Is there any way to edit the options and search patterns without using "Grep Highlight Editor"?  It is also not clear that it is doing nothing at all.  I'll take your word if you say it is not impacting performance in any way, of course, but from a user perspective it is non-obvious.

**Comment by krasa** [comment]
What are you trying to do? Change settings for the console?

Then you have 2 ways:

- File | Settings | Other Settings | Grep Console

- ![image](https://cloud.githubusercontent.com/assets/1160875/25008033/ba3d051a-2062-11e7-8dc8-ccf8b1375170.png)

**Comment by Mochnant** [comment]
Okay, I see.  So the Tools | Grep Highlight Editor windows that opens is the same settings windows that the icon next to the console accesses (the changes are reflected in both) but the OK button on Grep Highlight Editor also processes the editor window.

Thanks for the screenshot.  I had not noticed that option.  As for what I was trying to do, I was just trying to be sure that Grep Console wasn't scanning editor windows constantly that I had no interest in grepping.

I think this is cleared up now, thank you for the explanations.

**Comment by Mochnant** [comment]
Closing this issue as resolved.
