### ISSUE TITLE
Filter applied even if previous item matched and not set to continue

### ISSUE THREAD

**Issue by andrewkincaid** [krasa/GrepConsole#92]
Sometimes I just want to see lines that are highlighted.  To do this, I add a ".*" item as the last item and set to "Whole line" and "Filter out".  Previously, this worked.  It prints out only lines that were highlighted (by the previous items) and filters out anything that didn't match.  Now, it filters all lines out.  It's as if every item is set to "continue" and, therefore, the last rule always applies and everything is filtered out.  I'm using the latest version: 6.10.162.000.0

**Comment by krasa** [comment]
I cleaned some strange looking code, it seems it was a feature :-D

**Comment by krasa** [comment]
I will release it several days later, if you want to try it - https://github.com/krasa/GrepConsole/releases/download/7.0.162.000.1/GrepConsole.zip

**Comment by andrewkincaid** [comment]
It's working! Thank you so much!!!
-Andrew
 
--------- Original Message --------- Subject: Re: [krasa/GrepConsole] Filter applied even if previous item matched and not set to continue (#92)
