### ISSUE TITLE
Grep console modifies Run Configuration XMLs

### ISSUE THREAD

**Issue by turbanoff** [krasa/GrepConsole#94]
After updating plugin to v7.0 I noticed that grep console plugin add this line too all run configurations.

    <extension name="krasa.grepconsole.plugin.runConfiguration.GrepRunConfigurationExtension" selectedProfileId="1445619722828" />

We share run configurations between developers (commit XMLs to git) and it's forbidden to commit such changes.
Is it possible to disable this modification?

**Comment by krasa** [comment]
I will do something about it.

**Comment by krasa** [comment]
Please try it https://github.com/krasa/GrepConsole/releases/download/7.1.162.000.0/GrepConsole.zip

Those lines should be removed, but probably not from default run configurations, if you have changed any. It will need a manual change.


You should also disable this checkbox:
![image](https://user-images.githubusercontent.com/1160875/32344155-2a9648b0-c006-11e7-8fe8-8600bbf8fad0.png)
