### ISSUE TITLE
Enhancement - Add ability to filter matched text by line

### ISSUE THREAD

**Issue by sawser2k2** [krasa/GrepConsole#99]
I have a logger that adds session information to the front of log statements, and I don't have access to change the log configuration. 

I would be insanely helpful when monitoring the log if  I could hide that prepended information. 

For example - 
12-07-2017 09:35:41,975 INFO  [blah blah blah 500 characters of junk] Webservice call

becomes

12-07-2017 09:35:41,975 INFO  Webservice call

Thanks!

**Comment by krasa** [comment]
duplicates https://github.com/krasa/GrepConsole/issues/66
